Caleb/ljps-43
lanceljr/is212-LJPS pull request #52
Opened 2022-10-20 02:01 UTC by cnjk060598

## Context

JIRA ticket: https://g4t7.atlassian.net/jira/software/c/projects/LJPS/issues/LJPS-XXX

## Approach

### Before & After
**New confirmation Page** 
![image](https://user-images.githubusercontent.com/89075648/196855733-98e90e32-ec96-4916-ad53-a5a8bb66c4be.png)

## Checklist

- [x] My branch is up-to-date with the `main` branch
- [ ] Unit test written
- [ ] Acceptance Criteria considered and implemented

## Test Instruction

## Risks

2022-10-20 04:03 UTC, cnjk060598 commented
![image](https://user-images.githubusercontent.com/89075648/196853643-86027d82-e8aa-4e65-81e3-3e1f04a6437b.png)

Final View for Learning Journey confirmation page

2022-10-20 04:05 UTC, Randyyeo requested changes
Looks good! Nicely done. Just some comments

- Add the picture of confirmation page in the PR description
- Remove all commented code

2022-10-20 04:14 UTC, cnjk060598 commented
Removed commented lines

2022-10-22 07:33 UTC, Randyyeo approved these changes

2022-10-22 12:49 UTC, merged